/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as WorcesterImport } from './routes/worcester'
import { Route as HampshireImport } from './routes/hampshire'
import { Route as FranklinImport } from './routes/franklin'
import { Route as BerkshireImport } from './routes/berkshire'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const WorcesterRoute = WorcesterImport.update({
  path: '/worcester',
  getParentRoute: () => rootRoute,
} as any)

const HampshireRoute = HampshireImport.update({
  path: '/hampshire',
  getParentRoute: () => rootRoute,
} as any)

const FranklinRoute = FranklinImport.update({
  path: '/franklin',
  getParentRoute: () => rootRoute,
} as any)

const BerkshireRoute = BerkshireImport.update({
  path: '/berkshire',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/berkshire': {
      preLoaderRoute: typeof BerkshireImport
      parentRoute: typeof rootRoute
    }
    '/franklin': {
      preLoaderRoute: typeof FranklinImport
      parentRoute: typeof rootRoute
    }
    '/hampshire': {
      preLoaderRoute: typeof HampshireImport
      parentRoute: typeof rootRoute
    }
    '/worcester': {
      preLoaderRoute: typeof WorcesterImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  BerkshireRoute,
  FranklinRoute,
  HampshireRoute,
  WorcesterRoute,
])

/* prettier-ignore-end */
